apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pvc
  labels:
    app: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Adjust the size according to your needs
