apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-cpp-pvc
  labels:
    app: llama-cpp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Adjust the size according to your needs
