apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-volume-pvc
  labels:
    app: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Adjust the size according to your needs
