# .yamllint
extends: default

rules:
  line-length: disable
  document-start: disable
  indentation:
    indent-sequences: whatever

# Ignore certain directories or Helm template files
ignore: |
  llm-clients/openwebui/charts/**
  llm-clients/openwebui/templates/**/*.tpl
