---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-postgresql-secret
  labels:
    app: mlflow-postgresql
stringData:
  database-name: vectordb  # Change this with your own value
  database-password: vectordb  # Change this with your own value
  database-user: vectordb  # Change this with your own value
type: Opaque
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-postgresql-pvc
  labels:
    app: mlflow-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Adjust the size according to your needs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-postgresql-deployment
  labels:
    app: mlflow-postgresql
    app.kubernetes.io/part-of: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-postgresql
  template:
    metadata:
      labels:
        app: mlflow-postgresql
    spec:
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: mlflow-postgresql-pvc
      containers:
        - name: postgresql
          image: 'quay.io/rh-aiservices-bu/postgresql-15-pgvector-c9s:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: mlflow-postgresql-secret
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow-postgresql-secret
                  key: database-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mlflow-postgresql-secret
                  key: database-name
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - '--live'
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/pgsql/data
      restartPolicy: Always
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-postgresql-service
  labels:
    app: mlflow-postgresql
spec:
  type: ClusterIP
  selector:
    app: mlflow-postgresql
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: postgresql
