apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-cache
  labels:
    app: hf-tgi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Adjust the size according to your needs
