---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: attu-deployment
  labels:
    app: milvus
    app.kubernetes.io/part-of: MilvusDB
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attu
  template:
    metadata:
      labels:
        app: attu
    spec:
      containers:
      - name: attu
        image: zilliz/attu:v2.4.8
        imagePullPolicy: IfNotPresent
        env:
        - name: MILVUS_URL
          value: "milvus-service:19530"
        ports:
        - name: attu
          containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
      restartPolicy: Always
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: attu-service
  labels:
    app: milvus
spec:
  type: ClusterIP
  selector:
    app: attu
  ports:
  - name: attu
    protocol: TCP
    port: 3000
    targetPort: attu
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: attu-route
  labels:
    app: milvus
spec:
  to:
    kind: Service
    name: attu-service
    weight: 100
  port:
    targetPort: attu
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
