---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-pvc
  labels:
    app: milvus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the size according to your needs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-deployment
  labels:
    app: milvus
    app.kubernetes.io/part-of: MilvusDB
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      volumes:
        - name: etcd-volume
          persistentVolumeClaim:
            claimName: etcd-pvc
      containers:
        - name: etcd-container
          image: quay.io/coreos/etcd:v3.5.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2379
          command:
            - etcd
            - "-advertise-client-urls"
            - "http://127.0.0.1:2379"
            - "-listen-client-urls"
            - "http://0.0.0.0:2379"
            - "--data-dir"
            - /etcd
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 512Mi
          volumeMounts:
            - name: etcd-volume
              mountPath: /etcd
      restartPolicy: Always
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-service
  labels:
    app: milvus
spec:
  type: ClusterIP
  selector:
    app: etcd
  ports:
    - name: api
      protocol: TCP
      port: 2379
      targetPort: 2379
