---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-pvc
  labels:
    app: milvus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi   # Adjust the size according to your needs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-deployment
  labels:
    app: milvus
    app.kubernetes.io/part-of: MilvusDB
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
    spec:
      volumes:
        # - name: milvus-volume
        #   emptyDir: {}
        - name: milvus-volume
          persistentVolumeClaim:
            claimName: milvus-pvc
        - name: milvus-config-data
          configMap:
            name: milvus-config
      containers:
        - name: milvus-container
          image: milvusdb/milvus:v2.5.5
          imagePullPolicy: IfNotPresent
          env:
            - name: ETCD_ENDPOINTS
              value: etcd-service:2379
            - name: MINIO_ADDRESS
              value: milvus-minio-service:9000
            - name: MINIO_ACCESS_KEY
              value: minioadmin  # Make sure to use secure Access Key
            - name: MINIO_SECRET_KEY
              value: minioadmin  # Make sure to use secure Secret Key
          ports:
            - containerPort: 19530
          command:
            - milvus
            - run
            - standalone
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 512Mi
          volumeMounts:
            - name: milvus-volume
              mountPath: /var/lib/milvus
            - name: milvus-config-data
              mountPath: /milvus/configs/milvus.yaml
              subPath: milvus.yaml
              readOnly: true
      restartPolicy: Always
      # imagePullSecrets:
      #   - name: <your-secret-name>
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-service
  labels:
    app: milvus
spec:
  type: ClusterIP
  selector:
    app: milvus
  ports:
    - name: api
      protocol: TCP
      port: 19530
      targetPort: 19530
