apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    app: pgvector
stringData:
  database-name: vectordb  # Change this with your own value
  database-password: vectordb  # Change this with your own value
  database-user: vectordb  # Change this with your own value
type: Opaque
