apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  labels:
    app: pgvector
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Adjust the size according to your needs
