apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: pgvector
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: postgresql
